# Color Configuration

# Cursor colors
cursor #aaa7a0
cursor_text_color #272a2e

# The basic colors
foreground #d8dee0
background #272a2e
selection_foreground #272a2e
selection_background #aaa7a0

# The color table
color0 #39464e
color1 #9b6266
color2 #66766d
color3 #a69d7d
color4 #62727a
color5 #81757d
color6 #52645d
color7 #c8ced1
color8 #4b565d
color9 #9b6266
color10 #66766d
color11 #a69d7d
color12 #62727a
color13 #81757d
color14 #52645d
color15 #b9c1c5

# Marks
mark1_foreground #272a2e
mark1_background #81757d
mark2_foreground #272a2e
mark2_background #81757d
mark3_foreground #272a2e
mark3_background #566871

title_fg             #b9c1c5
title_bg             #23272b
margin_bg            #23272b
margin_fg            #b9c1c5
filler_bg            #23272b
removed_bg           #5e3f53
highlight_removed_bg #89556b
removed_margin_bg    #734a5f
added_bg             #475a51
highlight_added_bg   #628168
added_margin_bg      #734a5f
hunk_margin_bg       #23272b
hunk_bg              #23272b
search_bg            #766c62
search_fg            #d8dee0
select_bg            #3e5767
select_fg            #d8dee0
