base = #282828
mantle = #1d2021
crust = #1b1b1b
surface0 = #3c3836
surface1 = #504945
surface2 = #665c54
text = #ebdbb2
subtext0 = #bdae93
subtext1 = #d5c4a1
overlay0 = #928374
rosewater = #fbf1c7
flamingo = #fabd2f
pink = #d3869b
mauve = #b16286
red = #fb4934
maroon = #cc241d
peach = #fe8019
yellow = #fabd2f
green = #b8bb26
teal = #8ec07c
sky = #83a598
sapphire = #458588
blue = #83a598
lavender = #d3869b
