base = #2e3440
mantle = #272c36
crust = #242933
surface0 = #3b4252
surface1 = #434c5e
surface2 = #4c566a
text = #eceff4
subtext0 = #d8dee9
subtext1 = #e5e9f0
overlay0 = #616e88
rosewater = #d8dee9
flamingo = #ebcb8b
pink = #b48ead
mauve = #b48ead
red = #bf616a
maroon = #bf616a
peach = #d08770
yellow = #ebcb8b
green = #a3be8c
teal = #8fbcbb
sky = #88c0d0
sapphire = #81a1c1
blue = #81a1c1
lavender = #b48ead
