base = #282c34
mantle = #21252b
crust = #1e2127
surface0 = #2c323c
surface1 = #3e4451
surface2 = #545862
text = #abb2bf
subtext0 = #828997
subtext1 = #9da5b4
overlay0 = #5c6370
rosewater = #e06c75
flamingo = #e06c75
pink = #c678dd
mauve = #c678dd
red = #e06c75
maroon = #be5046
peach = #d19a66
yellow = #e5c07b
green = #98c379
teal = #56b6c2
sky = #56b6c2
sapphire = #61afef
blue = #61afef
lavender = #c678dd
