base = #191724
mantle = #16141f
crust = #12101a
surface0 = #26233a
surface1 = #403d52
surface2 = #524f67
text = #e0def4
subtext0 = #908caa
subtext1 = #c4a7e7
overlay0 = #6e6a86
rosewater = #ebbcba
flamingo = #eb6f92
pink = #eb6f92
mauve = #c4a7e7
red = #eb6f92
maroon = #b4637a
peach = #f6c177
yellow = #f6c177
green = #9ccfd8
teal = #9ccfd8
sky = #31748f
sapphire = #31748f
blue = #9ccfd8
lavender = #c4a7e7
