#################
### AUTOSTART ###
#################

#exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE
exec-once = waybar &
exec-once = mako &
exec-once = awww-daemon &
exec-once = wl-paste --watch cliphist store &
