#################
### AUTOSTART ###
#################

#exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE
exec-once = udiskie --automount --notify &
exec-once = waybar &
exec-once = mako &
exec-once = awww-daemon &
exec-once = wl-paste --watch cliphist store &
#exec-once = 9router --tray --skip-update
exec-once = 9router
exec-once = headroom proxy --port 8787 &
