###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
$browser = brave --ozone-platform=wayland --enable-features=UseOzonePlatform --password-store=basic --profile-directory="Default"
$discord = discord
$spotify = spotify-launcher
