return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      background = {
        light = "latte",
        dark = "mocha",
      },
      transparent_background = false,
      show_end_of_buffer = false,
      term_colors = false,
      dim_inactive = {
        enabled = true,
        shade = "dark",
        percentage = 0.15,
      },
      color_overrides = {
        mocha = {
          base = "#272a2e",
          mantle = "#23272b",
          crust = "#1e2226",
          surface0 = "#30363b",
          surface1 = "#39464e",
          surface2 = "#4b565d",
          text = "#d8dee0",
          subtext0 = "#b9c1c5",
          subtext1 = "#c8ced1",
          overlay0 = "#626d73",
          rosewater = "#aaa7a0",
          flamingo = "#a59a8b",
          pink = "#81757d",
          mauve = "#81757d",
          red = "#9b6266",
          maroon = "#89575b",
          peach = "#927d70",
          yellow = "#a69d7d",
          green = "#66766d",
          teal = "#52645d",
          sky = "#6b7c82",
          sapphire = "#566871",
          blue = "#62727a",
          lavender = "#81757d",
        },
      },
      integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        notify = false,
        mini = {
          enabled = true,
          indentscope_color = "",
        },
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-mocha",
    },
  },
}
